# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/HECC/HECC.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==HECC || ORIG_REF_NAME==HECC} -quiet] -quiet
