# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/asus/Desktop/finalFPGA/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_edgeDetection2_0_0/design_1_edgeDetection2_0_0.xci
# IP: The module: 'design_1_edgeDetection2_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/asus/Desktop/finalFPGA/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_edgeDetection2_0_0/src/cordic_0/cordic_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cordic_0 || ORIG_REF_NAME==cordic_0} -quiet] -quiet

# IP: c:/Users/asus/Desktop/finalFPGA/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_edgeDetection2_0_0/src/HECC/HECC.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==HECC || ORIG_REF_NAME==HECC} -quiet] -quiet

# IP: c:/Users/asus/Desktop/finalFPGA/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_edgeDetection2_0_0/design_1_edgeDetection2_0_0.xci
# IP: The module: 'design_1_edgeDetection2_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/asus/Desktop/finalFPGA/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_edgeDetection2_0_0/src/cordic_0/cordic_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cordic_0 || ORIG_REF_NAME==cordic_0} -quiet] -quiet

# IP: c:/Users/asus/Desktop/finalFPGA/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_edgeDetection2_0_0/src/HECC/HECC.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==HECC || ORIG_REF_NAME==HECC} -quiet] -quiet
