# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/asus/Desktop/finalFPGA/ip_repo/edgeDetection_1.0/src/HECC/HECC.xci
# IP: The module: 'HECC' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/asus/Desktop/finalFPGA/ip_repo/edgeDetection_1.0/src/HECC/HECC_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'HECC'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/asus/Desktop/finalFPGA/ip_repo/edgeDetection_1.0/src/HECC/HECC.xci
# IP: The module: 'HECC' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/asus/Desktop/finalFPGA/ip_repo/edgeDetection_1.0/src/HECC/HECC_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'HECC'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
